# Generated by Django 5.2.4 on 2025-08-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognome', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('numero_cartella', models.CharField(blank=True, max_length=50, verbose_name='N° cartella')),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='N° di telefono')),
                ('nazionalita', models.CharField(blank=True, max_length=100)),
                ('data_arrivo_italia', models.DateField(blank=True, null=True)),
                ('prima_visita', models.DateField(blank=True, null=True)),
                ('professione_origine', models.CharField(blank=True, max_length=200)),
                ('professione_italia', models.CharField(blank=True, max_length=200)),
                ('stp', models.CharField(blank=True, max_length=100)),
                ('esenzioni', models.CharField(blank=True, max_length=200)),
                ('motivo_migrazione', models.CharField(blank=True, choices=[('Lavoro', 'Lavoro'), ('Guerra', 'Guerra'), ('Politico', 'Politico'), ('Altro', 'Altro')], max_length=100)),
                ('ha_famiglia_in_patria', models.BooleanField(default=False)),
                ('ha_famiglia_in_italia', models.BooleanField(default=False)),
                ('ha_parenti_in_italia', models.BooleanField(default=False)),
                ('ha_amici_in_italia', models.BooleanField(default=False)),
                ('titolo_studio', models.CharField(blank=True, choices=[('Elementari', 'Elementari'), ('Medie', 'Medie'), ('Superiori', 'Superiori'), ('Università', 'Università')], max_length=50)),
                ('stile_vita', models.CharField(blank=True, choices=[('Regolare', 'Regolare con requisiti minimi'), ('Stabile', 'Stabile senza requisiti minimi'), ('Precario', 'Precario'), ('Comunita', 'Comunità/dormitori')], max_length=50)),
                ('occupazione', models.CharField(blank=True, choices=[('Stabile', 'Stabile'), ('Occasionale', 'Occasionale'), ('Disoccupato', 'Disoccupato')], max_length=50)),
                ('conoscenza_italiano', models.CharField(blank=True, choices=[('Scarsa', 'Scarsa (necessita traduzione)'), ('Sufficiente', 'Sufficiente'), ('Ottima', 'Ottima')], max_length=50)),
                ('seconda_lingua', models.CharField(blank=True, max_length=100)),
                ('anamnesi_familiare', models.TextField(blank=True)),
                ('anamnesi_patologica_remota', models.TextField(blank=True)),
                ('fumo', models.BooleanField(default=False)),
                ('alcool', models.BooleanField(default=False)),
                ('droghe', models.BooleanField(default=False, verbose_name='Sostanze stupefacenti')),
                ('terapia', models.TextField(blank=True)),
                ('farmaci_costosi', models.CharField(blank=True, max_length=200, verbose_name='Farmaci particolari/costosi')),
                ('motivo_visita', models.TextField(blank=True, verbose_name='Anamnesi patologica prossima/motivo della visita')),
                ('esame_obiettivo', models.TextField(blank=True)),
                ('programma', models.TextField(blank=True)),
                ('diario_clinico', models.TextField(blank=True)),
            ],
        ),
    ]
