# Generated by Django 5.2.4 on 2025-08-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='anamnesi_familiare',
            new_name='allergie',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='anamnesi_patologica_remota',
        ),
        migrations.AddField(
            model_name='patient',
            name='fam_altro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='fam_diabete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='fam_epilessia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='fam_infarto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='fam_ipertensione',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='fam_mal_immunologiche',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='fam_mal_renali',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='fam_neoplasia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='fam_stroke',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='fam_tbc_hiv_hbv_hcv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='rem_diabete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='rem_epilessia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='rem_hbv_hcv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='rem_hiv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='rem_infarto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='rem_ipertensione',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='rem_mal_immunologiche',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='rem_mal_renali',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='rem_neoplasia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='rem_stroke',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='rem_tbc',
            field=models.BooleanField(default=False),
        ),
    ]
